name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Python 2
    - name: Configure project for python 2
      run: PYTHON=python2 ./autogen.sh

    - name: Checking unit tests
      continue-on-error: true
      run: make check

    - uses: actions/upload-artifact@v2
      name: Upload generated logs on tests check for Python 2
      with:
        name: tests-logs-python2
        path: tests/*.log

    - name: Checking distribution unit tests
      continue-on-error: true
      run: make dist-check

    - uses: actions/upload-artifact@v2
      name: Upload generated logs on distribution tests check for Python 2
      with:
        name: dist-tests-logs-python2
        path: tests/*.log

    - name: Generate distribution package
      run: |
        make
        make dist

    - uses: actions/upload-artifact@v2
      name: Upload generated distribution package for Python 2
      with:
        name: dist-python2
        path: fleet-commander*.xz

    # Python 3
    - name: Configure project for python 3
      run: PYTHON=python3 ./autogen.sh

    - name: Checking unit tests
      continue-on-error: true
      run: make check

    - uses: actions/upload-artifact@v2
      name: Upload generated logs on tests check for Python 3
      with:
        name: tests-logs-python3
        path: tests/*.log

    - name: Checking distribution unit tests
      continue-on-error: true
      run: make dist-check

    - uses: actions/upload-artifact@v2
      name: Upload generated logs on distribution tests check for Python 3
      with:
        name: dist-tests-logs-python3
        path: tests/*.log

    - name: Generate distribution package
      run: |
        make
        make dist

    - uses: actions/upload-artifact@v2
      name: Upload generated distribution package for Python 3
      with:
        name: dist-python3
        path: fleet-commander*.xz
