name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["python2", "python3"]
    steps:
    - uses: actions/checkout@v2

    - name: Configure project for ${{ matrix.node }}
      run: PYTHON=${{ matrix.node }} ./autogen.sh

    - name: Checking unit tests
      continue-on-error: true
      run: make check

    - uses: actions/upload-artifact@v2
      name: Upload generated logs on tests check
      with:
        name: tests-logs-${{ matrix.node }}
        path: tests/*.log

    - name: Checking distribution unit tests
      continue-on-error: true
      run: make dist-check

    - uses: actions/upload-artifact@v2
      name: Upload generated logs on distribution tests check for ${{ matrix.node }}
      with:
        name: dist-tests-logs-${{ matrix.node }}
        path: tests/*.log

    - name: Generate distribution package
      run: |
        make
        make dist

    - uses: actions/upload-artifact@v2
      name: Upload generated distribution package for ${{ matrix.node }}
      with:
        name: dist-${{ matrix.node }}
        path: fleet-commander*.xz
