name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Python 2
    - name: Configure project for python 2
      run: PYTHON=python2 ./autogen-ci.sh

    - name: Checking unit tests
      run: make check

    - name: Checking distribution unit tests
      run: make dist-check

    - name: Generate distribution package
      run: |
        make
        make dist

    # Python 3
    - name: Configure project for python 3
      run: PYTHON=python3 ./autogen-ci.sh

    - name: Checking unit tests
      run: make check

    - name: Checking distribution unit tests
      run: make dist-check

    - name: Generate distribution package
      run: |
        make
        make dist
